name: Jest Tests

on: [pull_request]

jobs:
  Jest-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm test -- --ci --reporters=jest-junit

      - name: Upload Jest results
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: frontend/test-results/jest/results.xml
