#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run lint-staged only if there are changes in the frontend directory
if git diff --cached --name-only | grep -q "^frontend/"; then
  cd frontend && npx lint-staged
fi
