# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Ruby on Rails dependencies (Bundler)
  - package-ecosystem: "bundler"
    versioning-strategy: "auto"  # Added versioning strategy
    schedule:
      interval: "weekly"

    # If you're using Docker for development or production, you can also add:
  - package-ecosystem: "docker"
    versioning-strategy: "auto"  # Added versioning strategy
    schedule:
      interval: "weekly"

  # Existing configuration for devcontainers, if still needed
  - package-ecosystem: "devcontainers"
    versioning-strategy: "auto"  # Added versioning strategy
    schedule:
      interval: "weekly"

