# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Ruby on Rails dependencies (Bundler)
  - package-ecosystem: "bundler"
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"  # How often to check for updates
    versioning-strategy: "auto"  # How to update manifest version requirements

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"  # Location of Dockerfile
    schedule:
      interval: "weekly"  # How often to check for updates
    versioning-strategy: "auto"  # How to update manifest version requirements

  # Devcontainers dependencies
  - package-ecosystem: "devcontainers"

    directory: "/"  # Location of devcontainer.json
    schedule:
      interval: "weekly"  # How often to check for updates
    versioning-strategy: "auto"  # How to update manifest version requirements
