development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "placeholder") %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("PROD_REDIS_URL", "placeholder") %>
  channel_prefix: battle_stadium_production
