inherit_from: backend/.rubocop_todo.yml
inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml
AllCops:
  NewCops: enable
  Exclude:
    - frontend/**
    - .devcontainer/**
    - .github/**
    - .pnpm-store/**
    - .turbo/**
    - .vscode/**
    - node_modules/**
