inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'lib/tasks/**/*'
    - 'vendor/**/*'
    - 'frontend/**/*'
