inherit_from: .rubocop_todo.yml
inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml
  rubocop-github:
    - config/default.yml # generic Ruby rules and cops
    - config/rails.yml # Rails-specific rules and cops

plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "lib/tasks/**/*"
    - "vendor/**/*"
    - "frontend/**/*"
    - "sorbet/**"
    - "sorbet/**/*"
    - "frontend/**"
Style/Documentation:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: false

