# .ruby-lsp.yml
# Example configuration for Ruby LSP

# Enable or disable specific features
features:
  diagnostics: true
  formatting: true
  hover: true
  completion: true
  codeActions: true
  documentSymbols: true
  workspaceSymbols: true
  foldingRanges: true
  semanticHighlighting: true
  inlayHints: true
  onTypeFormatting: true
  signatureHelp: true
  rename: true
  references: true
  definition: true
  implementation: true
  typeDefinition: true
  documentHighlight: true
  documentLink: true
  codeLens: true
  selectionRange: true
  callHierarchy: true
  semanticTokens: true
  linkedEditingRange: true
  moniker: true
  prepareRename: true
  inlineValue: true
  inlineCompletion: true
  diagnosticRelatedInformation: true
  diagnosticTagSupport: true
  diagnosticCodeActionSupport: true
  diagnosticCodeLensSupport: true
  diagnosticDataSupport: true
  diagnosticDocumentSymbolSupport: true
  diagnosticWorkspaceSymbolSupport: true
  diagnosticFoldingRangeSupport: true
  diagnosticSemanticTokensSupport: true
  diagnosticInlayHintsSupport: true
  diagnosticRenameSupport: true
  diagnosticReferencesSupport: true
  diagnosticDefinitionSupport: true
  diagnosticImplementationSupport: true
  diagnosticTypeDefinitionSupport: true
  diagnosticDocumentHighlightSupport: true
  diagnosticDocumentLinkSupport: true
  diagnosticSelectionRangeSupport: true
  diagnosticCallHierarchySupport: true
  diagnosticLinkedEditingRangeSupport: true
  diagnosticMonikerSupport: true
  diagnosticPrepareRenameSupport: true
  diagnosticInlineValueSupport: true
  diagnosticInlineCompletionSupport: true
