version: "0.2"
ignorePaths:
  - db/schema.rb
  - Gemfile
  - Gemfile.lock
  - db/migrate
  - db/schema.rb
dictionaryDefinitions: []
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - ruby
  - rails
  - bash
  - typescript
  - node
  - markdown
  - lorem-ipsum
words:
  - autobuild
  - bytesize
  - fcontext
  - fdescribe
  - filesize
  - ILIKE
  - invalidcookie
  - isready
  - mikepenz
  - rag
  - resultset
  - reviewdog
  - rewax
  - rowan
  - rsa
  - Rswag
  - srand
  - swag
  - timestr
  - unsubscription
  - VERCEL
  - teamlists
  - tera
  - pokepaste
  - swaggerize
  - thatguyinabeanie
  - Escobar
  - Fuecoco
  - Butterfree
  - Clefable
  - Victreebel
  - Sandslash
  - Staryu
  - deepcode
ignoreWords: []
import: []
