version: "0.2"
ignorePaths:
  - db/schema.rb
dictionaryDefinitions: []
dictionaries: []
words:
  - bytesize
  - libpq
  - libvips
  - Rakefile
  - realpath
  - timestr
  - unsubscription
ignoreWords: []
import: []
