version: "0.2"
ignorePaths:
  - db/schema.rb
  - Gemfile
  - Gemfile.lock
dictionaryDefinitions: []
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - ruby
  - rails
  - bash
  - typescript
  - node
  - markdown
  - lorem-ipsum
words:
ignoreWords: []
import: []
