version: "0.2"
ignorePaths:
  - db/schema.rb
  - Gemfile
  - Gemfile.lock
  - db/migrate
  - db/schema.rb
dictionaryDefinitions: []
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - ruby
  - rails
  - bash
  - typescript
  - node
  - markdown
  - lorem-ipsum
words:
  - autobuild
  - bytesize
  - filesize
  - invalidcookie
  - isready
  - mikepenz
  - rag
  - resultset
  - reviewdog
  - rewax
  - rowan
  - rsa
  - Rswag
  - swag
  - timestr
  - unsubscription
  - VERCEL
ignoreWords: []
import: []
