version: "0.2"
ignorePaths:
  - db/schema.rb
dictionaryDefinitions: []
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - ruby
  - rails
  - bash
  - typescript
  - node
words:
ignoreWords: []
import: []
