services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    image: battle-stadium:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - battle-stadium:latest
    command: >
      bash -lc "
        rm -f tmp/pids/server.pid &&
        (bundle check || bundle install) &&
        (rails db:prepare || rails db:setup) &&
        (rails server -b '0.0.0.0' -p 3000) &&
        sleep infinity
      "
    volumes:
      - .:/workspaces/battle-stadium
      - bundle-data:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/fuecoco_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    tty: true
  frontend:
    tty: true
    image: battle-stadium-frontend:latest
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
      tags:
        - battle-stadium-frontend:latest
    command: sleep infinity
    volumes:
      - ./frontend:/workspaces/battle-stadium/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  postgres-data:
  bundle-data:
