services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuecoco-db-development
    ports:
      - 5432:5432

  # BATTLE STADIUM RAILS APP CONTAINER
  rails_api:
    image: thatguyinabeanie/battle-stadium/rails:dev-latest
    environment:
      DEV_ENVIRONMENT: devcontainer
    build:
      context: backend
      target: development
      tags:
        - thatguyinabeanie/battle-stadium/rails:dev-latest
    command: >
      bash -c "
        rm -f tmp/pids/server.pid && \
        (bundle check || bundle install) && \
        (bundle exec rails server -b 0.0.0.0 -p 3000 & ) && \
        sleep infinity
      "
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/up" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - ./backend:/battle-stadium
      - ./backend/tmp:/tmp
      - .zshrc:/root/.zshrc

  nextjs:
    image: thatguyinabeanie/battle-stadium/nextjs/dev:latest
    build:
      context: frontend
      target: nextjs
      tags:
        - thatguyinabeanie/battle-stadium/nextjs:dev-latest
    # command: npm install && (npm run dev & ) && sleep infinity
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/nextjs
      - ./frontend/tmp:/tmp
      - .zshrc:/root/.zshrc
      - node_modules:/nextjs/node_modules
    command: >
      bash -c "
        rm -f tmp/pids/server.pid && \
        (npm ci && npm run dev & ) && \
        sleep infinity
      "
volumes:
  postgres-data:
  node_modules:
  home:
