services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=fuecoco-db-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - 6379:6379

  # RAILS API - DEVELOPMENT CONTAINER
  backend:
    hostname: rails-api-container
    image: thatguyinabeanie/battle-stadium:dev-latest
    environment:
      RAILS_ENV: development
      PORT: 10000
      AUTO_START_RAILS: "true"
    build:
      context: backend
      dockerfile: Dockerfile.dev
      target: development
      tags:
        - thatguyinabeanie/battle-stadium:dev-latest
      cache_from:
        - thatguyinabeanie/battle-stadium:dev-latest
    env_file:
      - backend/.env
    tty: true
    stdin_open: true
    ports:
      - 10000:10000
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend/up"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - .:/battle-stadium
      - ./backend/.zshrc:/root/.zshenv
      - ./backend/.zshrc:/root/.zshrc

  # RAILS API - PRODUCTION CONTAINER
  backend-prod:
    hostname: rails-api-container
    platform: linux/amd64
    profiles:
      - production
    environment:
      RAILS_ENV: production
      PORT: 10000
    build:
      context: backend
      dockerfile: Dockerfile.prod
      target: production
      tags:
        - thatguyinabeanie/battle-stadium:latest
      cache_from:
        - thatguyinabeanie/battle-stadium:prod-cache-latest
    tty: true
    stdin_open: true
    ports:
      - 10001:10000
    env_file:
      - backend/.env
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10001/up"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s

  frontend:
    hostname: nextjs-container
    image: thatguyinabeanie/battle-stadium:frontend-dev-latest
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
      tags:
        - thatguyinabeanie/battle-stadium:frontend-dev-latest
    command: >
      zsh -c "rm -rf .next && bun install && bun dev && tail -f /dev/null"
    tty: true
    depends_on:
      - postgres
      - backend
    ports:
      - 3000:3000
      - 8080:3000
    volumes:
      - .:/battle-stadium
      - ./frontend/.zshrc:/root/.zshenv
      - ./frontend/.zshrc:/root/.zshrc

volumes:
  postgres-data:
