services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuecoco-db-development
    ports:
      - 5432:5432

  backend_base_image:
    image: thatguyinabeanie/battle-stadium:backend-base-latest
    build:
      context: .
      dockerfile: Dockerfile
      target: base-image
      tags:
        - thatguyinabeanie/battle-stadium:backend-base-latest

  # BATTLE STADIUM RAILS APP CONTAINER
  dev:
    image: thatguyinabeanie/battle-stadium:backend-dev-latest
    environment:
      DB_HOST: db
      DEV_ENVIRONMENT: devcontainer
    build:
      context: .
      target: development
      dockerfile: Dockerfile
      tags:
        - thatguyinabeanie/battle-stadium:backend-dev-latest
    command: >
      bash -c "
        rm -f tmp/pids/server.pid && \
        pnpm install --silent && \
        (pnpm dev &) && \
        sleep infinity
      "
    tty: true
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - db
      - backend_base_image
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/up" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - ./backend/:/battle-stadium/backend
      - ./frontend/:/battle-stadium/frontend
      - ./devcontainer/:/battle-stadium/devcontainer
      - ./github/:/battle-stadium/github
      - ./.sonarlint/:/battle-stadium/.sonarlint
      - ./.vscode/:/battle-stadium/.vscode
      - ./.gitignore:/battle-stadium/.gitignore
      - ./.node-version:/battle-stadium/.node-version
      - ./.nvmrc:/battle-stadium/.nvmrc
      - ./.tool-versions:/battle-stadium/.tool-versions
      - ./CODE_OF_CONDUCT.md:/battle-stadium/CODE_OF_CONDUCT.md
      - ./CONTRIBUTING.md:/battle-stadium/CONTRIBUTING.md
      - ./Dockerfile:/battle-stadium/Dockerfile
      - ./docker-compose.yml:/battle-stadium/docker-compose.yml
      - ./LICENSE:/battle-stadium/LICENSE
      - ./openapitools.json:/battle-stadium/openapitools.json
      - ./package.json:/battle-stadium/package.json
      - ./pnpm-workspace.yaml:/battle-stadium/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/battle-stadium/pnpm-lock.yaml
      - ./README.md:/battle-stadium/README.md
      - ./SECURITY.md:/battle-stadium/SECURITY.md
      - ./turbo.json:/battle-stadium/turbo.json
      - .zshrc:/root/.zshrc
      - turbo:/battle-stadium/.turbo
      - pnpm-store:/battle-stadium/.pnpm-store
volumes:
  postgres-data:
  node_modules:
  turbo:
  pnpm-store:
