services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuecoco-db-development
    ports:
      - 5432:5432

  backend_base_image:
    build:
      context: .
      dockerfile: Dockerfile
      target: base-image
      tags:
        - thatguyinabeanie/battle-stadium:backend-base-latest

  # BATTLE STADIUM RAILS APP CONTAINER
  dev:
    image: thatguyinabeanie/battle-stadium:backend-dev-latest
    environment:
      DEV_ENVIRONMENT: devcontainer
    build:
      context: .
      target: development
      dockerfile: Dockerfile
      tags:
        - thatguyinabeanie/battle-stadium:backend-dev-latest
    command: >
      bash -c "
        rm -f tmp/pids/server.pid && \
        pnpm install --silent && \
        (pnpm dev &) && \
        sleep infinity
      "
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
      - backend_base_image
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/up" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - ./:/battle-stadium
      - .zshrc:/root/.zshrc
volumes:
  postgres-data:
  node_modules:
