services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuecoco-db-dev
    ports:
      - 5432:5432

  # BATTLE STADIUM RAILS APP CONTAINER
  backend:
    image: thatguyinabeanie/battle-stadium:dev-latest
    environment:
      HOST_ENVIRONMENT: container
      DB_HOST: db
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
      tags:
        - thatguyinabeanie/battle-stadium:dev-latest
      cache_from:
        - thatguyinabeanie/battle-stadium:dev-latest
    command: >
      bash -c "
        rm -f tmp/pids/server.pid && \
        (bundle check || bundle install) && \
        tail -f /dev/null
      "
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/up" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - .:/battle-stadium
      - .zshrc:/root/.zshrc

  frontend:
    environment:
      HOST_ENVIRONMENT: container
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
      tags:
        - thatguyinabeanie/battle-stadium:frontend-dev-latest
    command: >
      bash -c "
        pnpm install --silent && \
        tail -f /dev/null
      "
    depends_on:
      - backend
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/battle-stadium
      - .zshrc:/root/.zshrcs
volumes:
  postgres-data:
