##
## BASE IMAGE WITH ASDF AND RUBY
##
FROM mcr.microsoft.com/devcontainers/ruby:3.3-bookworm AS base-image
WORKDIR /battle-stadium
COPY .ruby-version .

RUN apt-get update -qq && \
    apt-get --no-install-recommends install -y -q \
    build-essential \
    curl \
    git \
    libc6 \
    libpq-dev \
    libreadline-dev \
    libssl-dev \
    openssl \
    postgresql \
    ruby-dev \
    watchman \
    wget \
    zlib1g-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN gem update bundler


## DEVELOPMENT IMAGE
##
FROM base-image AS development
# FROM base-image AS development
WORKDIR /battle-stadium
COPY . .
RUN bundle check || bundle install
EXPOSE 10000
ENV RAILS_ENV=development
ENTRYPOINT ["/battle-stadium/bin/docker-entrypoint"]
CMD ["/battle-stadium/bin/docker-entrypoint"]
