services:

  # BATTLE STADIUM RAILS APP CONTAINER
  backend:
    image: thatguyinabeanie/battle-stadium:development_base
    build:
      context: .
      dockerfile: Dockerfile.dev
      tags:
        - thatguyinabeanie/battle-stadium:development_base
    command: >
      bash -lc "
        rm -f tmp/pids/server.pid &&
        (bundle check || bundle install) &&
        (rails db:prepare || rails db:setup) &&
        sleep infinity
      "
    volumes:
      - .:/workspaces/battle-stadium
      - bundle-data:/root/.bundle
      - ./tmp:/tmp
      - ./.bashrc:/root/.bashrc
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/fuecoco_db
      RAILS_DB_HOST: db
      RAILS_DB_USERNAME: postgres
      RAILS_DB_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    tty: true

  # BATTLE STADIUM PRODUCTION CONTAINER
  production:
    image: battle-stadium:latest
    profiles: ["production"]
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - battle-stadium:latest
    command: >
      bash -lc "
        rm -f tmp/pids/server.pid &&
        (bundle check || bundle install) &&
        (rails db:prepare || rails db:setup) &&
        sleep infinity
      "
    volumes:
      - .:/rails
      - bundle-data:/root/.bundle
    ports:
      - "4000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/fuecoco_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    tty: true

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"

volumes:
  postgres-data:
  bundle-data:
