services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  # BATTLE STADIUM RAILS APP CONTAINER
  rails_api:
    image: thatguyinabeanie/battle-stadium:development-base-latest
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      tags:
        - thatguyinabeanie/battle-stadium:development-latest
    command: sleep infinity
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/up" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - .:/workspaces/battle-stadium
      - ./tmp:/tmp
      - .zsh/.zshrc:/root/.zshrc

  nextjs:
    image: thatguyinabeanie/battle-stadium:nextjs-latest
    build:
      context: .
      dockerfile: Dockerfile.nextjs
      target: nextjs
      tags:
        - thatguyinabeanie/battle-stadium:nextjs-latest
    command: sleep infinity
    tty: true
    ports:
      - 5173:5173
    volumes:
      - .:/workspaces/battle-stadium
      - ./tmp:/tmp
      - .zsh/.zshrc:/root/.zshrc

volumes:
  postgres-data:
  home:
