services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build: .
    command: tail -f /dev/null
    # command: bash -c  "
        # rm -f tmp/pids/server.pid && \
        # bundle install && \
        # rails server -b '0.0.0.0'"
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rotom_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  # frontend:
  #   build: ./frontend/.
  #   command: npm run dev
  #   volumes:
  #     - .:/src
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
  #   profiles:
  #     - frontend
volumes:
  db-data:
