/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PasswordRequest
 */
export interface PasswordRequest {
  /**
   * Must be at least 8 characters
   * @type {string}
   * @memberof PasswordRequest
   */
  password: string;
  /**
   * Must match the password.
   * @type {string}
   * @memberof PasswordRequest
   */
  passwordConfirmation: string;
}

/**
 * Check if a given object implements the PasswordRequest interface.
 */
export function instanceOfPasswordRequest(
  value: object,
): value is PasswordRequest {
  if (!("password" in value) || value["password"] === undefined) return false;
  if (
    !("passwordConfirmation" in value) ||
    value["passwordConfirmation"] === undefined
  )
    return false;
  return true;
}

export function PasswordRequestFromJSON(json: any): PasswordRequest {
  return PasswordRequestFromJSONTyped(json, false);
}

export function PasswordRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PasswordRequest {
  if (json == null) {
    return json;
  }
  return {
    password: json["password"],
    passwordConfirmation: json["password_confirmation"],
  };
}

export function PasswordRequestToJSON(value?: PasswordRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    password: value["password"],
    password_confirmation: value["passwordConfirmation"],
  };
}
