/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Phase
 */
export interface Phase {
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  order: number;
  /**
   *
   * @type {string}
   * @memberof Phase
   */
  type?: string;
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  tournamentId: number;
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  numberOfRounds: number;
  /**
   *
   * @type {number}
   * @memberof Phase
   */
  bestOf: number;
  /**
   *
   * @type {Date}
   * @memberof Phase
   */
  startedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof Phase
   */
  endedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof Phase
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof Phase
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the Phase interface.
 */
export function instanceOfPhase(value: object): value is Phase {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("order" in value) || value["order"] === undefined) return false;
  if (!("tournamentId" in value) || value["tournamentId"] === undefined)
    return false;
  if (!("numberOfRounds" in value) || value["numberOfRounds"] === undefined)
    return false;
  if (!("bestOf" in value) || value["bestOf"] === undefined) return false;
  if (!("startedAt" in value) || value["startedAt"] === undefined) return false;
  if (!("endedAt" in value) || value["endedAt"] === undefined) return false;
  return true;
}

export function PhaseFromJSON(json: any): Phase {
  return PhaseFromJSONTyped(json, false);
}

export function PhaseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Phase {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    order: json["order"],
    type: json["type"] == null ? undefined : json["type"],
    tournamentId: json["tournament_id"],
    numberOfRounds: json["number_of_rounds"],
    bestOf: json["best_of"],
    startedAt: json["started_at"] == null ? null : new Date(json["started_at"]),
    endedAt: json["ended_at"] == null ? null : new Date(json["ended_at"]),
    createdAt:
      json["created_at"] == null ? undefined : new Date(json["created_at"]),
    updatedAt:
      json["updated_at"] == null ? undefined : new Date(json["updated_at"]),
  };
}

export function PhaseToJSON(value?: Phase | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    name: value["name"],
    order: value["order"],
    type: value["type"],
    tournament_id: value["tournamentId"],
    number_of_rounds: value["numberOfRounds"],
    best_of: value["bestOf"],
    started_at:
      value["startedAt"] == null
        ? null
        : (value["startedAt"] as any).toISOString(),
    ended_at:
      value["endedAt"] == null ? null : (value["endedAt"] as any).toISOString(),
    created_at:
      value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
    updated_at:
      value["updatedAt"] == null ? undefined : value["updatedAt"].toISOString(),
  };
}
