/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PostUser403Response
 */
export interface PostUser403Response {
  /**
   *
   * @type {string}
   * @memberof PostUser403Response
   */
  error?: string;
}

/**
 * Check if a given object implements the PostUser403Response interface.
 */
export function instanceOfPostUser403Response(value: object): value is PostUser403Response {
  return true;
}

export function PostUser403ResponseFromJSON(json: any): PostUser403Response {
  return PostUser403ResponseFromJSONTyped(json, false);
}

export function PostUser403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUser403Response {
  if (json == null) {
    return json;
  }
  return {
    error: json["error"] == null ? undefined : json["error"],
  };
}

export function PostUser403ResponseToJSON(value?: PostUser403Response | null): any {
  if (value == null) {
    return value;
  }
  return {
    error: value["error"],
  };
}
