/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UserDetails } from "./UserDetails";
import { UserDetailsFromJSON, UserDetailsFromJSONTyped, UserDetailsToJSON } from "./UserDetails";
import type { Session } from "./Session";
import { SessionFromJSON, SessionFromJSONTyped, SessionToJSON } from "./Session";

/**
 *
 * @export
 * @interface SessionAndUser
 */
export interface SessionAndUser {
  /**
   *
   * @type {Session}
   * @memberof SessionAndUser
   */
  session: Session;
  /**
   *
   * @type {UserDetails}
   * @memberof SessionAndUser
   */
  user: UserDetails;
}

/**
 * Check if a given object implements the SessionAndUser interface.
 */
export function instanceOfSessionAndUser(value: object): value is SessionAndUser {
  if (!("session" in value) || value["session"] === undefined) return false;
  if (!("user" in value) || value["user"] === undefined) return false;
  return true;
}

export function SessionAndUserFromJSON(json: any): SessionAndUser {
  return SessionAndUserFromJSONTyped(json, false);
}

export function SessionAndUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionAndUser {
  if (json == null) {
    return json;
  }
  return {
    session: SessionFromJSON(json["session"]),
    user: UserDetailsFromJSON(json["user"]),
  };
}

export function SessionAndUserToJSON(value?: SessionAndUser | null): any {
  if (value == null) {
    return value;
  }
  return {
    session: SessionToJSON(value["session"]),
    user: UserDetailsToJSON(value["user"]),
  };
}
