/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ChangePasswordRequest
 */
export interface ChangePasswordRequest {
  /**
   * Must be at least 8 characters
   * @type {string}
   * @memberof ChangePasswordRequest
   */
  password: string;
  /**
   * Must match the password.
   * @type {string}
   * @memberof ChangePasswordRequest
   */
  passwordConfirmation: string;
  /**
   * Your current password.
   * @type {string}
   * @memberof ChangePasswordRequest
   */
  currentPassword: string;
}

/**
 * Check if a given object implements the ChangePasswordRequest interface.
 */
export function instanceOfChangePasswordRequest(
  value: object,
): value is ChangePasswordRequest {
  if (!("password" in value) || value["password"] === undefined) return false;
  if (
    !("passwordConfirmation" in value) ||
    value["passwordConfirmation"] === undefined
  )
    return false;
  if (!("currentPassword" in value) || value["currentPassword"] === undefined)
    return false;
  return true;
}

export function ChangePasswordRequestFromJSON(
  json: any,
): ChangePasswordRequest {
  return ChangePasswordRequestFromJSONTyped(json, false);
}

export function ChangePasswordRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChangePasswordRequest {
  if (json == null) {
    return json;
  }
  return {
    password: json["password"],
    passwordConfirmation: json["password_confirmation"],
    currentPassword: json["current_password"],
  };
}

export function ChangePasswordRequestToJSON(
  value?: ChangePasswordRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    password: value["password"],
    password_confirmation: value["passwordConfirmation"],
    current_password: value["currentPassword"],
  };
}
