/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateSession
 */
export interface CreateSession {
  /**
   *
   * @type {string}
   * @memberof CreateSession
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof CreateSession
   */
  sessionToken?: string;
  /**
   *
   * @type {Date}
   * @memberof CreateSession
   */
  expiresAt?: Date;
}

/**
 * Check if a given object implements the CreateSession interface.
 */
export function instanceOfCreateSession(value: object): value is CreateSession {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  return true;
}

export function CreateSessionFromJSON(json: any): CreateSession {
  return CreateSessionFromJSONTyped(json, false);
}

export function CreateSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSession {
  if (json == null) {
    return json;
  }
  return {
    userId: json["user_id"],
    sessionToken: json["session_token"] == null ? undefined : json["session_token"],
    expiresAt: json["expires_at"] == null ? undefined : new Date(json["expires_at"]),
  };
}

export function CreateSessionToJSON(value?: CreateSession | null): any {
  if (value == null) {
    return value;
  }
  return {
    user_id: value["userId"],
    session_token: value["sessionToken"],
    expires_at: value["expiresAt"] == null ? undefined : value["expiresAt"].toISOString(),
  };
}
