/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetSessionRequest
 */
export interface GetSessionRequest {
  /**
   *
   * @type {string}
   * @memberof GetSessionRequest
   */
  token: string;
}

/**
 * Check if a given object implements the GetSessionRequest interface.
 */
export function instanceOfGetSessionRequest(value: object): value is GetSessionRequest {
  if (!("token" in value) || value["token"] === undefined) return false;
  return true;
}

export function GetSessionRequestFromJSON(json: any): GetSessionRequest {
  return GetSessionRequestFromJSONTyped(json, false);
}

export function GetSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSessionRequest {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"],
  };
}

export function GetSessionRequestToJSON(value?: GetSessionRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    token: value["token"],
  };
}
