/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import { UserFromJSON, UserFromJSONTyped, UserToJSON } from "./User";

/**
 *
 * @export
 * @interface PlayerDetails
 */
export interface PlayerDetails {
  /**
   *
   * @type {number}
   * @memberof PlayerDetails
   */
  id: number;
  /**
   *
   * @type {User}
   * @memberof PlayerDetails
   */
  user: User;
  /**
   *
   * @type {string}
   * @memberof PlayerDetails
   */
  inGameName: string;
}

/**
 * Check if a given object implements the PlayerDetails interface.
 */
export function instanceOfPlayerDetails(value: object): value is PlayerDetails {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("user" in value) || value["user"] === undefined) return false;
  if (!("inGameName" in value) || value["inGameName"] === undefined)
    return false;
  return true;
}

export function PlayerDetailsFromJSON(json: any): PlayerDetails {
  return PlayerDetailsFromJSONTyped(json, false);
}

export function PlayerDetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlayerDetails {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    user: UserFromJSON(json["user"]),
    inGameName: json["in_game_name"],
  };
}

export function PlayerDetailsToJSON(value?: PlayerDetails | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    user: UserToJSON(value["user"]),
    in_game_name: value["inGameName"],
  };
}
