/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface Pokemon
 */
export interface Pokemon {
  /**
   *
   * @type {number}
   * @memberof Pokemon
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  nickname?: string | null
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  ability: string
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  teraType: string
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  nature: string
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  heldItem: string | null
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  move1: string | null
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  move2: string | null
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  move3: string | null
  /**
   *
   * @type {string}
   * @memberof Pokemon
   */
  move4: string | null
}

/**
 * Check if a given object implements the Pokemon interface.
 */
export function instanceOfPokemon(value: object): value is Pokemon {
  if (!("id" in value) || value["id"] === undefined) return false
  if (!("name" in value) || value["name"] === undefined) return false
  if (!("ability" in value) || value["ability"] === undefined) return false
  if (!("teraType" in value) || value["teraType"] === undefined) return false
  if (!("nature" in value) || value["nature"] === undefined) return false
  if (!("heldItem" in value) || value["heldItem"] === undefined) return false
  if (!("move1" in value) || value["move1"] === undefined) return false
  if (!("move2" in value) || value["move2"] === undefined) return false
  if (!("move3" in value) || value["move3"] === undefined) return false
  if (!("move4" in value) || value["move4"] === undefined) return false
  return true
}

export function PokemonFromJSON(json: any): Pokemon {
  return PokemonFromJSONTyped(json, false)
}

export function PokemonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pokemon {
  if (json == null) {
    return json
  }
  return {
    id: json["id"],
    name: json["name"],
    nickname: json["nickname"] == null ? undefined : json["nickname"],
    ability: json["ability"],
    teraType: json["tera_type"],
    nature: json["nature"],
    heldItem: json["held_item"],
    move1: json["move1"],
    move2: json["move2"],
    move3: json["move3"],
    move4: json["move4"],
  }
}

export function PokemonToJSON(value?: Pokemon | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value["id"],
    name: value["name"],
    nickname: value["nickname"],
    ability: value["ability"],
    tera_type: value["teraType"],
    nature: value["nature"],
    held_item: value["heldItem"],
    move1: value["move1"],
    move2: value["move2"],
    move3: value["move3"],
    move4: value["move4"],
  }
}
