/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SessionResponseSession
 */
export interface SessionResponseSession {
  /**
   *
   * @type {string}
   * @memberof SessionResponseSession
   */
  token: string;
  /**
   *
   * @type {string}
   * @memberof SessionResponseSession
   */
  userId: string;
  /**
   *
   * @type {Date}
   * @memberof SessionResponseSession
   */
  expiresAt: Date;
}

/**
 * Check if a given object implements the SessionResponseSession interface.
 */
export function instanceOfSessionResponseSession(value: object): value is SessionResponseSession {
  if (!("token" in value) || value["token"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("expiresAt" in value) || value["expiresAt"] === undefined) return false;
  return true;
}

export function SessionResponseSessionFromJSON(json: any): SessionResponseSession {
  return SessionResponseSessionFromJSONTyped(json, false);
}

export function SessionResponseSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionResponseSession {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"],
    userId: json["user_id"],
    expiresAt: new Date(json["expires_at"]),
  };
}

export function SessionResponseSessionToJSON(value?: SessionResponseSession | null): any {
  if (value == null) {
    return value;
  }
  return {
    token: value["token"],
    user_id: value["userId"],
    expires_at: value["expiresAt"].toISOString(),
  };
}
