/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SessionSession
 */
export interface SessionSession {
  /**
   *
   * @type {string}
   * @memberof SessionSession
   */
  token: string;
  /**
   *
   * @type {string}
   * @memberof SessionSession
   */
  userId: string;
  /**
   *
   * @type {Date}
   * @memberof SessionSession
   */
  expiresAt: Date;
}

/**
 * Check if a given object implements the SessionSession interface.
 */
export function instanceOfSessionSession(value: object): value is SessionSession {
  if (!("token" in value) || value["token"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("expiresAt" in value) || value["expiresAt"] === undefined) return false;
  return true;
}

export function SessionSessionFromJSON(json: any): SessionSession {
  return SessionSessionFromJSONTyped(json, false);
}

export function SessionSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionSession {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"],
    userId: json["user_id"],
    expiresAt: new Date(json["expires_at"]),
  };
}

export function SessionSessionToJSON(value?: SessionSession | null): any {
  if (value == null) {
    return value;
  }
  return {
    token: value["token"],
    user_id: value["userId"],
    expires_at: value["expiresAt"].toISOString(),
  };
}
