/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SessionResponseSession } from "./SessionResponseSession";
import {
  SessionResponseSessionFromJSON,
  SessionResponseSessionFromJSONTyped,
  SessionResponseSessionToJSON,
} from "./SessionResponseSession";
import type { UserDetails } from "./UserDetails";
import { UserDetailsFromJSON, UserDetailsFromJSONTyped, UserDetailsToJSON } from "./UserDetails";

/**
 *
 * @export
 * @interface SessionResponse
 */
export interface SessionResponse {
  /**
   *
   * @type {SessionResponseSession}
   * @memberof SessionResponse
   */
  session: SessionResponseSession;
  /**
   *
   * @type {UserDetails}
   * @memberof SessionResponse
   */
  user: UserDetails;
}

/**
 * Check if a given object implements the SessionResponse interface.
 */
export function instanceOfSessionResponse(value: object): value is SessionResponse {
  if (!("session" in value) || value["session"] === undefined) return false;
  if (!("user" in value) || value["user"] === undefined) return false;
  return true;
}

export function SessionResponseFromJSON(json: any): SessionResponse {
  return SessionResponseFromJSONTyped(json, false);
}

export function SessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionResponse {
  if (json == null) {
    return json;
  }
  return {
    session: SessionResponseSessionFromJSON(json["session"]),
    user: UserDetailsFromJSON(json["user"]),
  };
}

export function SessionResponseToJSON(value?: SessionResponse | null): any {
  if (value == null) {
    return value;
  }
  return {
    session: SessionResponseSessionToJSON(value["session"]),
    user: UserDetailsToJSON(value["user"]),
  };
}
