/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface UserRequest
 */
export interface UserRequest {
  /**
   *
   * @type {string}
   * @memberof UserRequest
   */
  username: string
  /**
   *
   * @type {string}
   * @memberof UserRequest
   */
  pronouns: string
  /**
   *
   * @type {string}
   * @memberof UserRequest
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof UserRequest
   */
  firstName: string
  /**
   *
   * @type {string}
   * @memberof UserRequest
   */
  lastName: string
  /**
   * Your current password.
   * @type {string}
   * @memberof UserRequest
   */
  currentPassword: string
  /**
   *
   * @type {number}
   * @memberof UserRequest
   */
  id?: number
}

/**
 * Check if a given object implements the UserRequest interface.
 */
export function instanceOfUserRequest(value: object): value is UserRequest {
  if (!("username" in value) || value["username"] === undefined) return false
  if (!("pronouns" in value) || value["pronouns"] === undefined) return false
  if (!("email" in value) || value["email"] === undefined) return false
  if (!("firstName" in value) || value["firstName"] === undefined) return false
  if (!("lastName" in value) || value["lastName"] === undefined) return false
  if (!("currentPassword" in value) || value["currentPassword"] === undefined) return false
  return true
}

export function UserRequestFromJSON(json: any): UserRequest {
  return UserRequestFromJSONTyped(json, false)
}

export function UserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRequest {
  if (json == null) {
    return json
  }
  return {
    username: json["username"],
    pronouns: json["pronouns"],
    email: json["email"],
    firstName: json["first_name"],
    lastName: json["last_name"],
    currentPassword: json["current_password"],
    id: json["id"] == null ? undefined : json["id"],
  }
}

export function UserRequestToJSON(value?: UserRequest | null): any {
  if (value == null) {
    return value
  }
  return {
    username: value["username"],
    pronouns: value["pronouns"],
    email: value["email"],
    first_name: value["firstName"],
    last_name: value["lastName"],
    current_password: value["currentPassword"],
    id: value["id"],
  }
}
