/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { Organization, TournamentDetails, User } from "../models/index";
import {
  OrganizationFromJSON,
  OrganizationToJSON,
  TournamentDetailsFromJSON,
  TournamentDetailsToJSON,
  UserFromJSON,
  UserToJSON,
} from "../models/index";

export interface DeleteOrganizationRequest {
  id: number;
}

export interface GetOrganizationRequest {
  id: number;
}

export interface ListOrganizationStaffRequest {
  id: number;
}

export interface PatchOrganizationRequest {
  id: number;
  organization?: Organization;
}

export interface PatchOrganizationTournamentRequest {
  organizationId: number;
  id: number;
  tournamentDetails?: TournamentDetails;
}

export interface PostOrganizationRequest {
  organization: Organization;
}

export interface PostOrganizationTournamentRequest {
  organizationId: number;
  tournamentDetails?: TournamentDetails;
}

/**
 *
 */
export class OrganizationsApi extends runtime.BaseAPI {
  /**
   * Deletes an organization.
   * Delete Organization
   */
  async deleteOrganizationRaw(
    requestParameters: DeleteOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling deleteOrganization().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v1/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"]))),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Deletes an organization.
   * Delete Organization
   */
  async deleteOrganization(id: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.deleteOrganizationRaw({ id: id }, initOverrides);
  }

  /**
   * Retrieves a specific organization.
   * Show Organization
   */
  async getOrganizationRaw(
    requestParameters: GetOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Organization>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getOrganization().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v1/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"]))),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
  }

  /**
   * Retrieves a specific organization.
   * Show Organization
   */
  async getOrganization(id: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
    const response = await this.getOrganizationRaw({ id: id }, initOverrides);
    return await response.value();
  }

  /**
   * Retrieves a list of staff members for a specific organization.
   * List Organization Staff
   */
  async listOrganizationStaffRaw(
    requestParameters: ListOrganizationStaffRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<User>>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling listOrganizationStaff().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v1/organizations/{id}/staff`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters["id"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserFromJSON));
  }

  /**
   * Retrieves a list of staff members for a specific organization.
   * List Organization Staff
   */
  async listOrganizationStaff(
    id: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<User>> {
    const response = await this.listOrganizationStaffRaw({ id: id }, initOverrides);
    return await response.value();
  }

  /**
   * List Organizations
   */
  async listOrganizationsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Organization>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v1/organizations`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationFromJSON));
  }

  /**
   * List Organizations
   */
  async listOrganizations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Organization>> {
    const response = await this.listOrganizationsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Updates an existing organization.
   * Update Organization
   */
  async patchOrganizationRaw(
    requestParameters: PatchOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Organization>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling patchOrganization().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/v1/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"]))),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: OrganizationToJSON(requestParameters["organization"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
  }

  /**
   * Updates an existing organization.
   * Update Organization
   */
  async patchOrganization(
    id: number,
    organization?: Organization,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Organization> {
    const response = await this.patchOrganizationRaw({ id: id, organization: organization }, initOverrides);
    return await response.value();
  }

  /**
   * Updates an existing tournament for a given organization.
   * Update Tournament
   */
  async patchOrganizationTournamentRaw(
    requestParameters: PatchOrganizationTournamentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TournamentDetails>> {
    if (requestParameters["organizationId"] == null) {
      throw new runtime.RequiredError(
        "organizationId",
        'Required parameter "organizationId" was null or undefined when calling patchOrganizationTournament().',
      );
    }

    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling patchOrganizationTournament().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/v1/organizations/{organization_id}/tournaments/{id}`
          .replace(`{${"organization_id"}}`, encodeURIComponent(String(requestParameters["organizationId"])))
          .replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"]))),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: TournamentDetailsToJSON(requestParameters["tournamentDetails"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TournamentDetailsFromJSON(jsonValue));
  }

  /**
   * Updates an existing tournament for a given organization.
   * Update Tournament
   */
  async patchOrganizationTournament(
    organizationId: number,
    id: number,
    tournamentDetails?: TournamentDetails,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TournamentDetails> {
    const response = await this.patchOrganizationTournamentRaw(
      { organizationId: organizationId, id: id, tournamentDetails: tournamentDetails },
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Creates a new organization.
   * Create Organization
   */
  async postOrganizationRaw(
    requestParameters: PostOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Organization>> {
    if (requestParameters["organization"] == null) {
      throw new runtime.RequiredError(
        "organization",
        'Required parameter "organization" was null or undefined when calling postOrganization().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/v1/organizations`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: OrganizationToJSON(requestParameters["organization"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
  }

  /**
   * Creates a new organization.
   * Create Organization
   */
  async postOrganization(
    organization: Organization,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Organization> {
    const response = await this.postOrganizationRaw({ organization: organization }, initOverrides);
    return await response.value();
  }

  /**
   * Creates a new tournament for a given organization.
   * Create Tournament
   */
  async postOrganizationTournamentRaw(
    requestParameters: PostOrganizationTournamentRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TournamentDetails>> {
    if (requestParameters["organizationId"] == null) {
      throw new runtime.RequiredError(
        "organizationId",
        'Required parameter "organizationId" was null or undefined when calling postOrganizationTournament().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/v1/organizations/{organization_id}/tournaments`.replace(
          `{${"organization_id"}}`,
          encodeURIComponent(String(requestParameters["organizationId"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: TournamentDetailsToJSON(requestParameters["tournamentDetails"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TournamentDetailsFromJSON(jsonValue));
  }

  /**
   * Creates a new tournament for a given organization.
   * Create Tournament
   */
  async postOrganizationTournament(
    organizationId: number,
    tournamentDetails?: TournamentDetails,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TournamentDetails> {
    const response = await this.postOrganizationTournamentRaw(
      { organizationId: organizationId, tournamentDetails: tournamentDetails },
      initOverrides,
    );
    return await response.value();
  }
}
