/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { RegisterUserRequest, RegistrationResponse } from "../models/index";
import {
  RegisterUserRequestFromJSON,
  RegisterUserRequestToJSON,
  RegistrationResponseFromJSON,
  RegistrationResponseToJSON,
} from "../models/index";

export interface RegisterUserOperationRequest {
  registerUserRequest?: RegisterUserRequest;
}

/**
 *
 */
export class RegistrationApi extends runtime.BaseAPI {
  /**
   * Registers a new user
   * Registers a new user
   */
  async registerUserRaw(
    requestParameters: RegisterUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RegistrationResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/v1/auth`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: RegisterUserRequestToJSON(requestParameters["registerUserRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => RegistrationResponseFromJSON(jsonValue));
  }

  /**
   * Registers a new user
   * Registers a new user
   */
  async registerUser(
    requestParameters: RegisterUserOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RegistrationResponse> {
    const response = await this.registerUserRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
