/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { UserLoginRequest } from "../models/index";
import { UserLoginRequestFromJSON, UserLoginRequestToJSON } from "../models/index";

export interface LoginUserRequest {
  userLoginRequest?: UserLoginRequest;
}

/**
 *
 */
export class SessionsApi extends runtime.BaseAPI {
  /**
   * Logs in a User.
   * Login
   */
  async loginUserRaw(
    requestParameters: LoginUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/login`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: UserLoginRequestToJSON(requestParameters["userLoginRequest"]),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Logs in a User.
   * Login
   */
  async loginUser(
    requestParameters: LoginUserRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.loginUserRaw(requestParameters, initOverrides);
  }
}
