---
openapi: 3.0.1
info:
  title: Battle Stadium API V1
  version: v1
paths: {}
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: https://api.battlestadium.gg/api/v1
components:
  responses:
    NotFound:
      description: not found
  securitySchemes:
    Bearer:
      description: JWT key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
  parameters:
    Page:
      name: page
      in: query
      type: integer
      description: Page number for pagination
      required: true
    PerPage:
      name: per_page
      in: query
      type: integer
      description: Number of items per page for pagination
      required: true
  schemas:
    Format:
      type: object
      title: Format
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Game:
      type: object
      title: Game
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
      - id
      - name
    GameDetail:
      type: object
      title: Game Details
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        formats:
          type: array
          items:
            "$ref": "#/components/schemas/Format"
      required:
      - id
      - name
      - formats
    User:
      type: object
      title: User
      properties:
        username:
          type: string
        pronouns:
          type: string
        image_url:
          type: string
          nullable: true
        id:
          type: string
          format: uuid
      required:
      - username
      - pronouns
      - id
      - username
      - pronouns
    UserDetails:
      type: object
      title: User Details
      properties:
        username:
          type: string
        pronouns:
          type: string
        image_url:
          type: string
          nullable: true
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        id:
          type: string
          format: uuid
      required:
      - id
      - email
      - first_name
      - last_name
      - username
      - pronouns
    UserMe:
      type: object
      title: User Me
      properties:
        username:
          type: string
        pronouns:
          type: string
        image_url:
          type: string
          nullable: true
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        id:
          type: string
          format: uuid
        organizations:
          type: array
          items:
            "$ref": "#/components/schemas/Organization"
      required:
      - organizations
      - id
      - email
      - first_name
      - last_name
      - username
      - pronouns
    UserPostRequest:
      type: object
      title: User Request
      properties:
        username:
          type: string
        pronouns:
          type: string
        image_url:
          type: string
          nullable: true
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        id:
          type: string
          format: uuid
      required:
      - email
      - first_name
      - last_name
      - username
      - pronouns
    UserRequest:
      type: object
      title: User Request
      properties:
        username:
          type: string
        pronouns:
          type: string
        image_url:
          type: string
          nullable: true
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        id:
          type: string
          format: uuid
      required:
      - email
      - first_name
      - last_name
      - username
      - pronouns
    RegistrationResponse:
      type: object
      title: Registration Response
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        pronouns:
          type: string
          nullable: true
        jti:
          type: string
          format: jwt
        name:
          type: string
          nullable: true
        image:
          type: string
          nullable: true
        admin:
          type: boolean
      required:
      - id
      - email
      - username
      - first_name
      - last_name
      - created_at
      - updated_at
      - pronouns
      - jti
      - name
      - image
    Organization:
      type: object
      title: Organization
      properties:
        owner:
          "$ref": "#/components/schemas/User"
          nullable: true
        description:
          type: string
          nullable: true
        logo_url:
          type: string
          nullable: true
          format: uri
        partner:
          type: boolean
        slug:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
      - id
      - name
      - owner
      - description
      - logo_url
      - slug
    OrganizationDetails:
      type: object
      title: Organization Details
      properties:
        owner:
          "$ref": "#/components/schemas/User"
          nullable: true
        description:
          type: string
          nullable: true
        logo_url:
          type: string
          nullable: true
          format: uri
        partner:
          type: boolean
        slug:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
      - id
      - name
      - owner
      - description
      - logo_url
      - slug
    Tournament:
      type: object
      title: Tournament
      properties:
        start_at:
          type: string
          format: date-time
          nullable: true
        organization:
          "$ref": "#/components/schemas/Organization"
        format:
          "$ref": "#/components/schemas/Format"
        game:
          "$ref": "#/components/schemas/Game"
        id:
          type: integer
          format: int64
        name:
          type: string
        player_cap:
          type: integer
          nullable: true
        player_count:
          type: integer
        end_at:
          type: string
          format: date-time
          nullable: true
        started_at:
          type: string
          format: date-time
          nullable: true
        ended_at:
          type: string
          format: date-time
          nullable: true
        registration_start_at:
          type: string
          format: date-time
          nullable: true
        registration_end_at:
          type: string
          format: date-time
          nullable: true
        late_registration:
          type: boolean
      required:
      - id
      - name
      - player_cap
      - organization
      - format
      - game
      - start_at
      - player_count
      - registration_start_at
      - registration_end_at
      - late_registration
    TournamentDetails:
      type: object
      title: Tournament Details
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        autostart:
          type: boolean
        start_at:
          type: string
          format: date-time
          nullable: true
        end_at:
          type: string
          format: date-time
          nullable: true
        organization:
          "$ref": "#/components/schemas/Organization"
        format:
          "$ref": "#/components/schemas/Format"
        game:
          "$ref": "#/components/schemas/Game"
        check_in_start_at:
          type: string
          format: date-time
          nullable: true
        late_registration:
          type: boolean
        teamlists_required:
          type: boolean
        open_team_sheets:
          type: boolean
        player_cap:
          type: integer
          nullable: true
        player_count:
          type: integer
        started_at:
          type: string
          format: date-time
          nullable: true
        ended_at:
          type: string
          format: date-time
          nullable: true
        registration_start_at:
          type: string
          format: date-time
          nullable: true
        registration_end_at:
          type: string
          format: date-time
          nullable: true
      required:
      - id
      - name
      - player_cap
      - organization
      - format
      - game
      - start_at
      - player_count
      - registration_start_at
      - registration_end_at
      - late_registration
      - start_at
      - player_cap
      - autostart
      - teamlists_required
      - open_team_sheets
      - check_in_start_at
      - late_registration
      - registration_start_at
      - registration_end_at
    Pokemon:
      type: object
      title: Pokemon
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nickname:
          type: string
          nullable: true
        ability:
          type: string
        tera_type:
          type: string
        nature:
          type: string
        held_item:
          type: string
          nullable: true
        move1:
          type: string
          nullable: true
        move2:
          type: string
          nullable: true
        move3:
          type: string
          nullable: true
        move4:
          type: string
          nullable: true
      required:
      - id
      - name
      - ability
      - tera_type
      - nature
      - held_item
      - move1
      - move2
      - move3
      - move4
    PlayerRequest:
      type: object
      title: Player Request
      properties:
        user_id:
          type: string
          format: uuid
        in_game_name:
          type: string
      required:
      - user_id
      - in_game_name
    Player:
      type: object
      title: Player
      properties:
        id:
          type: integer
          format: int64
        user:
          "$ref": "#/components/schemas/User"
        in_game_name:
          type: string
      required:
      - id
      - user
      - in_game_name
    PlayerDetails:
      type: object
      title: Player Details
      properties:
        id:
          type: integer
          format: int64
        user:
          "$ref": "#/components/schemas/User"
        in_game_name:
          type: string
      required:
      - id
      - user
      - in_game_name
    Round:
      type: object
      title: Round
      properties:
        id:
          type: integer
          format: int64
        phase_id:
          type: integer
          format: int64
        round_number:
          type: integer
          format: int64
        started_at:
          type: string
          format: date-time
          nullable: true
        ended_at:
          type: string
          format: date-time
          nullable: true
      required:
      - id
      - phase_id
      - round_number
      - started_at
      - ended_at
    Phase:
      type: object
      title: Phase
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        order:
          type: integer
          format: int64
        type:
          type: string
        tournament_id:
          type: integer
          format: int64
        number_of_rounds:
          type: integer
        best_of:
          type: integer
        started_at:
          type: string
          format: date-time
          nullable: true
        ended_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - name
      - order
      - tournament_id
      - number_of_rounds
      - best_of
      - started_at
      - ended_at
    PhaseDetails:
      type: object
      title: Phase Details
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        order:
          type: integer
          format: int64
        type:
          type: string
        tournament_id:
          type: integer
          format: int64
        number_of_rounds:
          type: integer
        best_of:
          type: integer
        started_at:
          type: string
          format: date-time
          nullable: true
        ended_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        players:
          type: array
          items:
            "$ref": "#/components/schemas/Player"
        rounds:
          type: array
          items:
            "$ref": "#/components/schemas/Round"
      required:
      - id
      - name
      - order
      - tournament_id
      - number_of_rounds
      - best_of
      - started_at
      - ended_at
      - players
      - rounds
    GameRequest:
      type: object
      title: GameRequest
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
      - name
    TournamentRequest:
      type: object
      title: Tournament Request
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        game_id:
          type: integer
          format: int64
        format_id:
          type: integer
          format: int64
        autostart:
          type: boolean
        start_at:
          type: string
          format: date-time
        player_cap:
          type: integer
          nullable: true
        registration_start_at:
          type: string
          format: date-time
          nullable: true
        registration_end_at:
          type: string
          format: date-time
          nullable: true
        late_registration:
          type: boolean
        check_in_start_at:
          type: string
          format: date-time
          nullable: true
        open_team_sheets:
          type: boolean
        teamlists_required:
          type: boolean
      required:
      - name
      - game_id
      - format_id
      - autostart
      - start_at
      - player_cap
      - registration_start_at
      - registration_end_at
      - late_registration
      - check_in_start_at
      - open_team_sheets
      - teamlists_required
    TournamentPostRequest:
      type: object
      title: Tournament Post Request
      properties:
        organization_id:
          type: integer
          format: int64
        name:
          type: string
        game_id:
          type: integer
          format: int64
        format_id:
          type: integer
          format: int64
        autostart:
          type: boolean
        start_at:
          type: string
          format: date-time
        player_cap:
          type: integer
          nullable: true
        registration_start_at:
          type: string
          format: date-time
          nullable: true
        registration_end_at:
          type: string
          format: date-time
          nullable: true
        late_registration:
          type: boolean
        check_in_start_at:
          type: string
          format: date-time
          nullable: true
        open_team_sheets:
          type: boolean
        teamlists_required:
          type: boolean
      required:
      - organization_id
      - name
      - game_id
      - format_id
      - autostart
      - player_cap
      - registration_start_at
      - registration_end_at
      - late_registration
      - check_in_start_at
      - open_team_sheets
      - teamlists_required
    GetSessionRequest:
      type: object
      title: Get Session Params
      properties:
        token:
          type: string
          format: jwt
      required:
      - token
    CreateSession:
      type: object
      title: Create Session
      properties:
        user_id:
          type: string
          format: uuid
        session_token:
          type: string
          format: jwt
        expires_at:
          type: string
          format: date-time
      required:
      - user_id
    Session:
      type: object
      title: Session
      properties:
        username:
          type: string
        token:
          type: string
          format: jwt
        user_id:
          type: string
          format: uuid
        expires_at:
          type: string
          format: date-time
      required:
      - token
      - user_id
      - expires_at
    SessionAndUser:
      type: object
      title: Session And User
      properties:
        session:
          "$ref": "#/components/schemas/Session"
        user:
          "$ref": "#/components/schemas/UserDetails"
      required:
      - session
      - user
    Error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
    Message:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    Pagination:
      type: object
      properties:
        current_page:
          type: integer
        next_page:
          type: integer
          nullable: true
        prev_page:
          type: integer
          nullable: true
        total_pages:
          type: integer
        total_count:
          type: integer
      required:
      - current_page
      - next_page
      - prev_page
      - total_pages
      - total_count
