name: Dev Docker Image

on:
  push:
    branches:
      - main
    paths:
      - backend/BASE_IMAGE_VERSION

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-backend-dev:
    runs-on: ubuntu-latest
    env:
      MAJOR: -1
      MINOR: -1
      PATCH: -1

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: thatguyinabeanie
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from file
        id: extract_version
        run: |
          VERSION=$(cat backend/BASE_IMAGE_VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          MAJOR=$(echo $VERSION | cut -d'.' -f1)
          MINOR=$(echo $VERSION | cut -d'.' -f2)
          PATCH=$(echo $VERSION | cut -d'.' -f3)
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MAJOR.$MINOR" >> $GITHUB_ENV
          echo "PATCH=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      - name: Build & Push Docker Image
        if: github.ref == 'refs/heads/main' || github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          target: development
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=thatguyinabeanie/battle-stadium:dev-latest
          cache-to: type=registry,ref=thatguyinabeanie/battle-stadium:dev-latest,mode=max
          tags: |
            thatguyinabeanie/battle-stadium:dev-latest
            thatguyinabeanie/battle-stadium:dev-${{env.MAJOR}}
            thatguyinabeanie/battle-stadium:dev-${{env.MINOR}}
            thatguyinabeanie/battle-stadium:dev-${{env.PATCH}}
            ghcr.io/thatguyinabeanie/battle-stadium:dev-latest
            ghcr.io/thatguyinabeanie/battle-stadium:dev-${{env.MAJOR}}
            ghcr.io/thatguyinabeanie/battle-stadium:dev-${{env.MINOR}}
            ghcr.io/thatguyinabeanie/battle-stadium:dev-${{env.PATCH}}

