name: Branch Docker Image

on:
  pull_request:
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          file: Dockerfile.prod
          target: pre-production
          platforms: linux/amd64
          push: true
          cache-to: type=registry,ref=${{ github.repository }}:dev-cache-latest
          cache-from: type=registry,ref=${{ github.repository }}:dev-cache-latest,modes=max
          tags: |
            ${{ github.repository }}:${{ github.head_ref}}
            ghcr.io/${{ github.repository }}:${{ github.head_ref}}
