name: Rails API Docker Image PROD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: thatguyinabeanie
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from file
        id: extract_version
        run: |
          VERSION=$(cat backend/BASE_IMAGE_VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          MAJOR=$(echo $VERSION | cut -d'.' -f1)
          MINOR=$(echo $VERSION | cut -d'.' -f2)
          PATCH=$(echo $VERSION | cut -d'.' -f3)
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MAJOR.$MINOR" >> $GITHUB_ENV
          echo "PATCH=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      - name: Build & Push Docker Image
        if: github.ref == 'refs/heads/main' || github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          file: Dockerfile.prod
          target: pre-production
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=thatguyinabeanie/battle-stadium:prod-cache-latest
          cache-to: type=registry,ref=thatguyinabeanie/battle-stadium:prod-cache-latest,mode=max
          tags: |
            thatguyinabeanie/battle-stadium:latest
            ghcr.io/thatguyinabeanie/battle-stadium:latest

      - name: Deploy Rails API to Render.com
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
