name: Rails API Docker Image PROD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: thatguyinabeanie
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Push Docker Image
        if: github.ref == 'refs/heads/main' || github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          file: Dockerfile.prod
          target: pre-production
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=thatguyinabeanie/battle-stadium:prod-cache-latest
          cache-to: type=registry,ref=thatguyinabeanie/battle-stadium:prod-cache-latest,mode=max
          tags: |
            thatguyinabeanie/battle-stadium:latest
            ghcr.io/thatguyinabeanie/battle-stadium:latest

      - name: Call render.com deploy webhook
        run: curl -X POST -d {} ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

