name: Docker Images

on:
  push:
    branches:
      - "**"
  release:
    types:
      - published

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          # - linux/arm64

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        if: github.event_name == 'release'
        id: extract_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "MAJOR=${GITHUB_REF#refs/tags/v}" | cut -d'.' -f1 >> $GITHUB_ENV

      - name: Build ${{ matrix.platform }} Docker Image
        if: github.ref != 'refs/heads/main' && github.event_name != 'release'
        uses: docker/build-push-action@v6
        with:
          context: backend
          target: development
          platforms: ${{ matrix.platform }}
          push: false
