name: Build and Push Development Docker Image

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        if: github.event_name == 'release'
        id: extract_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "MAJOR=${GITHUB_REF#refs/tags/v}" | cut -d'.' -f1 >> $GITHUB_ENV
          echo "MINOR=${GITHUB_REF#refs/tags/v}" | cut -d'.' -f1,2 >> $GITHUB_ENV

      - name: Set default values for version
        if: github.event_name != 'release'
        run: |
          echo "VERSION=latest" >> $GITHUB_ENV
          echo "MAJOR=latest" >> $GITHUB_ENV
          echo "MINOR=latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.dev
          target: development_base_image
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/battle-stadium:development-base-latest
            ${{ secrets.DOCKER_USERNAME }}/battle-stadium:development-base-${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/battle-stadium:development-base-${{ env.MINOR }}
            ${{ secrets.DOCKER_USERNAME }}/battle-stadium:development-base-${{ env.MAJOR }}
            ghcr.io/${{ github.repository_owner }}/battle-stadium:development-base-latest
            ghcr.io/${{ github.repository_owner }}/battle-stadium:development-base-${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/battle-stadium:development-base-${{ env.MINOR }}
            ghcr.io/${{ github.repository_owner }}/battle-stadium:development-base-${{ env.MAJOR }}

      - name: Post build cleanup
        run: docker builder prune --force
