name: Build and Push Development Docker Image

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_and_push_amd64:
    uses: ./.github/workflows/docker-build.yml
    with:
      platform: linux/amd64

  build_and_push_arm64:
    uses: ./.github/workflows/docker-build.yml
    with:
      platform: linux/arm64
