name: Docker Images

on:
  push:
    paths:
      - BASE_IMAGE_VERSION
    branches:
      - main

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from file
        id: read_version
        run: |
          VERSION=$(cat ./BASE_IMAGE_VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_MAJOR=${VERSION%%.*}" >> $GITHUB_ENV
          echo "VERSION_MINOR=${VERSION%.*}" >> $GITHUB_ENV

      - name: Build ${{ matrix.platform }} Docker Image
        if: false
        uses: docker/build-push-action@v6
        with:
          target: base-image
          platforms: ${{ matrix.platform }}
          push: true
          cache-from: type=registry,ref=thatguyinabeanie/battle-stadium:base-buildcache
          cache-to: type=registry,ref=thatguyinabeanie/battle-stadium:base-buildcache,mode=max
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/battle-stadium:base-latest
            ${{ secrets.DOCKER_USERNAME }}/battle-stadium:base-${{ env.VERSION_MAJOR }}
            ${{ secrets.DOCKER_USERNAME }}/battle-stadium:base-${{ env.VERSION_MINOR }}
            ${{ secrets.DOCKER_USERNAME }}/battle-stadium:base-${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:base-latest
            ghcr.io/${{ github.repository }}:base-${{ env.VERSION_MAJOR }}
            ghcr.io/${{ github.repository }}:base-${{ env.VERSION_MINOR }}
            ghcr.io/${{ github.repository }}:base-${{ env.VERSION }}
