name: Front End CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
        working-directory: frontend

      - name: Generate Prisma Client
        run: bun prisma:generate
        working-directory: frontend

      - name: Run Tests
        run: bun test
        working-directory: frontend
        env:
          CI: true

      # - name: Publish Test Report
      #   uses: mikepenz/action-junit-report@v4
      #   if: always()
      #   with:
      #     include_passed: true
      #     report_paths: 'frontend/test-results/jest/results.xml'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        if: ${{ !cancelled() }}
        with:
          directory: frontend/coverage
          flags: bun
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Upload test results to Codecov
      #   if: ${{ !cancelled() }}
      #   uses: codecov/test-results-action@v1
      #   with:
      #     directory: frontend/test-results
      #     files: '**/*.xml'
      #     flags: bun
      #     token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
        working-directory: frontend

      - name: Run Lint
        run: bun lint
        working-directory: frontend

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
        working-directory: frontend

      - name: Run Prettier Check
        run: bun prettier:check
        working-directory: frontend

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
        working-directory: frontend

      - name: Generate Prisma Client
        run: bun prisma:generate
        working-directory: frontend

      - name: Run Type Check
        run: bun tsc
        working-directory: frontend
