name: Front End CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
          cache-dependency-path: ./frontend/bun.lockb
          check-latest: true

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --silent
        working-directory: frontend

      - name: Run Jest tests
        run: bun jest
        working-directory: frontend
        env:
          CI: true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          include_passed: true
          report_paths: 'frontend/test-results/jest/results.xml'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        if: ${{ !cancelled() }}
        with:
          directory: frontend/coverage
          flags: jest
          name: codecov-umbrella
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          directory: frontend/test-results
          files: '**/*.xml'
          flags: jest
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
          cache-dependency-path: ./frontend/bun.lockb
          check-latest: true

      - name: Install Dependencies
        run: bun install --silent
        working-directory: frontend

      - name: Run Lint
        run: bun lint
        working-directory: frontend

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
          cache-dependency-path: ./frontend/bun.lockb
          check-latest: true

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --silent
        working-directory: frontend

      - name: Run Prettier Check
        run: bun prettier:check
        working-directory: frontend

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
          cache-dependency-path: ./frontend/bun.lockb
          check-latest: true

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --silent
        working-directory: frontend

      - name: Run Type Check
        run: bun tsc
        working-directory: frontend
