name: Front End CI

on: [pull_request]

permissions:
  checks: write

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
          check-latest: true

      - name: Install Dependencies
        run: pnpm install --silent
        working-directory: frontend

      - name: Run Jest tests
        run: pnpm test
        working-directory: frontend
        env:
          CI: true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          include_passed: true
          report_paths: 'frontend/test-results/jest/results.xml'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        if: ${{ !cancelled() }}
        with:
          directory: frontend/coverage
          flags: jest
          name: codecov-umbrella
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          directory: frontend/test-results/jest
          file: results.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
          check-latest: true

      - name: Install Dependencies
        run: pnpm install --silent
        working-directory: frontend

      - name: Run Lint
        run: pnpm lint
        working-directory: frontend

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.node-version
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml
          check-latest: true

      - name: Install Dependencies
        run: pnpm install --silent
        working-directory: frontend

      - name: Run Prettier Check
        run: pnpm prettier:check
        working-directory: frontend
