name: Jest Tests

on: [pull_request]

jobs:
  Jest-Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Prepare Jest
        run: |
          mkdir -p frontend/test-results/jest

      - name: Run Jest tests
        env:
          CI: true
        run: pnpm install --silent && pnpm jest"

      - name: Upload Jest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: frontend/test-results/jest/results.xml
