name: Ruby Audit

on: [pull_request]

jobs:

  Ruby-Audit:
    env:
      RAILS_ENV: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true # This automatically caches gems, no need for manual cache steps
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bundle check || bundle install
      - name: Run Ruby Audit
        run: bundle exec ruby-audit check
