name: Tests

on: [pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: fuecoco_db
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install dependencies
        run: |
          mkdir -p ./vendor/bundle
          bundle config set path 'vendor/bundle'
          bundle install
      - name: Prepare database
        run: |
          bundle exec rake db:create db:migrate db:schema:load --trace
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/fuecoco_db_test
      - name: Run RSpec tests
        run: bundle exec rspec
