name: Tests

on: [pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run Jest tests
        run: |
          cd frontend
          npm run test
      - name: Upload Jest results
        uses: actions/upload-artifact@v4
        if: always() # This ensures the test results are uploaded even if the Jest step fails
        with:
          name: jest-results
          path: frontend/test-results/jest/results.xml
